server:
  port: 8070
spring:
  application:
    name: priceservice
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/mydb?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    show-sql: true
    

