server:
  port: 8080
spring:
  application:
    name: taxservice
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/mydb?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    show-sql: true
  zipkin:
    base-url: http://localhost:9411/        
  sleuth:
    sampler:
      probability: 1
    feign:
      enabled: true      

    
eureka:
 instance:
   preferIpAddress: true
   instance-id:
 client:
    serviceUrl:
      defaultZone: http://192.168.133.1:8761/eureka/    
      